<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Libmem.NET.SmokeTests</AssemblyName>
    <RootNamespace>Libmem.NET.SmokeTests</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>x64;x86</Platforms><PlatformTarget>$(Platform)</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Libmem.NET">
      <HintPath>..\..\artifacts\managed\$(Platform)\$(Configuration)\Libmem.NET.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\artifacts\managed\$(Platform)\$(Configuration)\Ijwhost.dll"
          Link="Ijwhost.dll"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\artifacts\managed\$(Platform)\$(Configuration)\libmem.dll"
          Link="libmem.dll"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
